// BCP 47 / ISO 639-1 주요 언어 코드 + 영문/원어 표기.
// 사용자가 영어 코드 모를 때 검색용.
export type LanguageEntry = {
  code: string;          // e.g. "fr", "zh-CN"
  englishName: string;   // "French"
  nativeName: string;    // "Français"
  region?: string;       // "France", "China" (선택)
};

export const LANGUAGE_CODES: LanguageEntry[] = [
  { code: 'af', englishName: 'Afrikaans', nativeName: 'Afrikaans', region: 'South Africa' },
  { code: 'am', englishName: 'Amharic', nativeName: 'አማርኛ', region: 'Ethiopia' },
  { code: 'ar', englishName: 'Arabic', nativeName: 'العربية' },
  { code: 'az', englishName: 'Azerbaijani', nativeName: 'Azərbaycan', region: 'Azerbaijan' },
  { code: 'be', englishName: 'Belarusian', nativeName: 'Беларуская', region: 'Belarus' },
  { code: 'bg', englishName: 'Bulgarian', nativeName: 'Български', region: 'Bulgaria' },
  { code: 'bn', englishName: 'Bengali', nativeName: 'বাংলা', region: 'Bangladesh' },
  { code: 'bo', englishName: 'Tibetan', nativeName: 'བོད་སྐད་' },
  { code: 'bs', englishName: 'Bosnian', nativeName: 'Bosanski', region: 'Bosnia' },
  { code: 'ca', englishName: 'Catalan', nativeName: 'Català', region: 'Catalonia' },
  { code: 'ceb', englishName: 'Cebuano', nativeName: 'Cebuano', region: 'Philippines' },
  { code: 'co', englishName: 'Corsican', nativeName: 'Corsu' },
  { code: 'cs', englishName: 'Czech', nativeName: 'Čeština', region: 'Czech Republic' },
  { code: 'cy', englishName: 'Welsh', nativeName: 'Cymraeg', region: 'Wales' },
  { code: 'da', englishName: 'Danish', nativeName: 'Dansk', region: 'Denmark' },
  { code: 'de', englishName: 'German', nativeName: 'Deutsch', region: 'Germany' },
  { code: 'de-AT', englishName: 'German (Austria)', nativeName: 'Deutsch (Österreich)', region: 'Austria' },
  { code: 'de-CH', englishName: 'German (Switzerland)', nativeName: 'Deutsch (Schweiz)', region: 'Switzerland' },
  { code: 'dv', englishName: 'Dhivehi', nativeName: 'ދިވެހި', region: 'Maldives' },
  { code: 'el', englishName: 'Greek', nativeName: 'Ελληνικά', region: 'Greece' },
  { code: 'en', englishName: 'English', nativeName: 'English' },
  { code: 'en-GB', englishName: 'English (UK)', nativeName: 'English (UK)', region: 'United Kingdom' },
  { code: 'en-US', englishName: 'English (US)', nativeName: 'English (US)', region: 'United States' },
  { code: 'en-AU', englishName: 'English (Australia)', nativeName: 'English (Australia)', region: 'Australia' },
  { code: 'en-CA', englishName: 'English (Canada)', nativeName: 'English (Canada)', region: 'Canada' },
  { code: 'en-IN', englishName: 'English (India)', nativeName: 'English (India)', region: 'India' },
  { code: 'eo', englishName: 'Esperanto', nativeName: 'Esperanto' },
  { code: 'es', englishName: 'Spanish', nativeName: 'Español', region: 'Spain' },
  { code: 'es-MX', englishName: 'Spanish (Mexico)', nativeName: 'Español (México)', region: 'Mexico' },
  { code: 'es-AR', englishName: 'Spanish (Argentina)', nativeName: 'Español (Argentina)', region: 'Argentina' },
  { code: 'es-CO', englishName: 'Spanish (Colombia)', nativeName: 'Español (Colombia)', region: 'Colombia' },
  { code: 'et', englishName: 'Estonian', nativeName: 'Eesti', region: 'Estonia' },
  { code: 'eu', englishName: 'Basque', nativeName: 'Euskara' },
  { code: 'fa', englishName: 'Persian', nativeName: 'فارسی', region: 'Iran' },
  { code: 'fi', englishName: 'Finnish', nativeName: 'Suomi', region: 'Finland' },
  { code: 'fil', englishName: 'Filipino', nativeName: 'Filipino', region: 'Philippines' },
  { code: 'fo', englishName: 'Faroese', nativeName: 'Føroyskt', region: 'Faroe Islands' },
  { code: 'fr', englishName: 'French', nativeName: 'Français', region: 'France' },
  { code: 'fr-CA', englishName: 'French (Canada)', nativeName: 'Français (Canada)', region: 'Canada' },
  { code: 'fr-BE', englishName: 'French (Belgium)', nativeName: 'Français (Belgique)', region: 'Belgium' },
  { code: 'fr-CH', englishName: 'French (Switzerland)', nativeName: 'Français (Suisse)', region: 'Switzerland' },
  { code: 'fy', englishName: 'Frisian', nativeName: 'Frysk' },
  { code: 'ga', englishName: 'Irish', nativeName: 'Gaeilge', region: 'Ireland' },
  { code: 'gd', englishName: 'Scottish Gaelic', nativeName: 'Gàidhlig', region: 'Scotland' },
  { code: 'gl', englishName: 'Galician', nativeName: 'Galego' },
  { code: 'gu', englishName: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'ha', englishName: 'Hausa', nativeName: 'Hausa' },
  { code: 'haw', englishName: 'Hawaiian', nativeName: 'ʻŌlelo Hawaiʻi', region: 'Hawaii' },
  { code: 'he', englishName: 'Hebrew', nativeName: 'עברית', region: 'Israel' },
  { code: 'hi', englishName: 'Hindi', nativeName: 'हिन्दी', region: 'India' },
  { code: 'hmn', englishName: 'Hmong', nativeName: 'Hmoob' },
  { code: 'hr', englishName: 'Croatian', nativeName: 'Hrvatski', region: 'Croatia' },
  { code: 'ht', englishName: 'Haitian Creole', nativeName: 'Kreyòl ayisyen', region: 'Haiti' },
  { code: 'hu', englishName: 'Hungarian', nativeName: 'Magyar', region: 'Hungary' },
  { code: 'hy', englishName: 'Armenian', nativeName: 'Հայերեն', region: 'Armenia' },
  { code: 'id', englishName: 'Indonesian', nativeName: 'Bahasa Indonesia', region: 'Indonesia' },
  { code: 'ig', englishName: 'Igbo', nativeName: 'Igbo', region: 'Nigeria' },
  { code: 'is', englishName: 'Icelandic', nativeName: 'Íslenska', region: 'Iceland' },
  { code: 'it', englishName: 'Italian', nativeName: 'Italiano', region: 'Italy' },
  { code: 'iu', englishName: 'Inuktitut', nativeName: 'ᐃᓄᒃᑎᑐᑦ' },
  { code: 'ja', englishName: 'Japanese', nativeName: '日本語', region: 'Japan' },
  { code: 'jv', englishName: 'Javanese', nativeName: 'Basa Jawa', region: 'Indonesia' },
  { code: 'ka', englishName: 'Georgian', nativeName: 'ქართული', region: 'Georgia' },
  { code: 'kk', englishName: 'Kazakh', nativeName: 'Қазақ', region: 'Kazakhstan' },
  { code: 'km', englishName: 'Khmer', nativeName: 'ខ្មែរ', region: 'Cambodia' },
  { code: 'kn', englishName: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'ko', englishName: 'Korean', nativeName: '한국어', region: 'South Korea' },
  { code: 'ku', englishName: 'Kurdish', nativeName: 'Kurdî' },
  { code: 'ky', englishName: 'Kyrgyz', nativeName: 'Кыргызча', region: 'Kyrgyzstan' },
  { code: 'la', englishName: 'Latin', nativeName: 'Latina' },
  { code: 'lb', englishName: 'Luxembourgish', nativeName: 'Lëtzebuergesch', region: 'Luxembourg' },
  { code: 'lo', englishName: 'Lao', nativeName: 'ລາວ', region: 'Laos' },
  { code: 'lt', englishName: 'Lithuanian', nativeName: 'Lietuvių', region: 'Lithuania' },
  { code: 'lv', englishName: 'Latvian', nativeName: 'Latviešu', region: 'Latvia' },
  { code: 'mg', englishName: 'Malagasy', nativeName: 'Malagasy', region: 'Madagascar' },
  { code: 'mi', englishName: 'Maori', nativeName: 'Māori', region: 'New Zealand' },
  { code: 'mk', englishName: 'Macedonian', nativeName: 'Македонски', region: 'North Macedonia' },
  { code: 'ml', englishName: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'mn', englishName: 'Mongolian', nativeName: 'Монгол', region: 'Mongolia' },
  { code: 'mr', englishName: 'Marathi', nativeName: 'मराठी' },
  { code: 'ms', englishName: 'Malay', nativeName: 'Bahasa Melayu', region: 'Malaysia' },
  { code: 'mt', englishName: 'Maltese', nativeName: 'Malti', region: 'Malta' },
  { code: 'my', englishName: 'Burmese', nativeName: 'မြန်မာ', region: 'Myanmar' },
  { code: 'ne', englishName: 'Nepali', nativeName: 'नेपाली', region: 'Nepal' },
  { code: 'nl', englishName: 'Dutch', nativeName: 'Nederlands', region: 'Netherlands' },
  { code: 'nl-BE', englishName: 'Dutch (Belgium)', nativeName: 'Nederlands (België)', region: 'Belgium' },
  { code: 'no', englishName: 'Norwegian', nativeName: 'Norsk', region: 'Norway' },
  { code: 'ny', englishName: 'Chichewa', nativeName: 'Chichewa' },
  { code: 'or', englishName: 'Odia', nativeName: 'ଓଡ଼ିଆ' },
  { code: 'pa', englishName: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
  { code: 'pl', englishName: 'Polish', nativeName: 'Polski', region: 'Poland' },
  { code: 'ps', englishName: 'Pashto', nativeName: 'پښتو', region: 'Afghanistan' },
  { code: 'pt', englishName: 'Portuguese', nativeName: 'Português', region: 'Portugal' },
  { code: 'pt-BR', englishName: 'Portuguese (Brazil)', nativeName: 'Português (Brasil)', region: 'Brazil' },
  { code: 'ro', englishName: 'Romanian', nativeName: 'Română', region: 'Romania' },
  { code: 'ru', englishName: 'Russian', nativeName: 'Русский', region: 'Russia' },
  { code: 'rw', englishName: 'Kinyarwanda', nativeName: 'Kinyarwanda', region: 'Rwanda' },
  { code: 'sd', englishName: 'Sindhi', nativeName: 'سنڌي' },
  { code: 'si', englishName: 'Sinhala', nativeName: 'සිංහල', region: 'Sri Lanka' },
  { code: 'sk', englishName: 'Slovak', nativeName: 'Slovenčina', region: 'Slovakia' },
  { code: 'sl', englishName: 'Slovenian', nativeName: 'Slovenščina', region: 'Slovenia' },
  { code: 'sm', englishName: 'Samoan', nativeName: 'Gagana Samoa', region: 'Samoa' },
  { code: 'sn', englishName: 'Shona', nativeName: 'Shona', region: 'Zimbabwe' },
  { code: 'so', englishName: 'Somali', nativeName: 'Soomaali', region: 'Somalia' },
  { code: 'sq', englishName: 'Albanian', nativeName: 'Shqip', region: 'Albania' },
  { code: 'sr', englishName: 'Serbian', nativeName: 'Српски', region: 'Serbia' },
  { code: 'st', englishName: 'Sesotho', nativeName: 'Sesotho', region: 'Lesotho' },
  { code: 'su', englishName: 'Sundanese', nativeName: 'Basa Sunda' },
  { code: 'sv', englishName: 'Swedish', nativeName: 'Svenska', region: 'Sweden' },
  { code: 'sw', englishName: 'Swahili', nativeName: 'Kiswahili', region: 'East Africa' },
  { code: 'ta', englishName: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'te', englishName: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'tg', englishName: 'Tajik', nativeName: 'Тоҷикӣ', region: 'Tajikistan' },
  { code: 'th', englishName: 'Thai', nativeName: 'ไทย', region: 'Thailand' },
  { code: 'ti', englishName: 'Tigrinya', nativeName: 'ትግርኛ', region: 'Eritrea' },
  { code: 'tk', englishName: 'Turkmen', nativeName: 'Türkmen', region: 'Turkmenistan' },
  { code: 'tr', englishName: 'Turkish', nativeName: 'Türkçe', region: 'Turkey' },
  { code: 'tt', englishName: 'Tatar', nativeName: 'Татар' },
  { code: 'ug', englishName: 'Uyghur', nativeName: 'ئۇيغۇرچە' },
  { code: 'uk', englishName: 'Ukrainian', nativeName: 'Українська', region: 'Ukraine' },
  { code: 'ur', englishName: 'Urdu', nativeName: 'اردو', region: 'Pakistan' },
  { code: 'uz', englishName: 'Uzbek', nativeName: 'Oʻzbek', region: 'Uzbekistan' },
  { code: 'vi', englishName: 'Vietnamese', nativeName: 'Tiếng Việt', region: 'Vietnam' },
  { code: 'xh', englishName: 'Xhosa', nativeName: 'isiXhosa', region: 'South Africa' },
  { code: 'yi', englishName: 'Yiddish', nativeName: 'ייִדיש' },
  { code: 'yo', englishName: 'Yoruba', nativeName: 'Yorùbá', region: 'Nigeria' },
  { code: 'zh-CN', englishName: 'Chinese (Simplified)', nativeName: '简体中文', region: 'China' },
  { code: 'zh-TW', englishName: 'Chinese (Traditional)', nativeName: '繁體中文', region: 'Taiwan' },
  { code: 'zh-HK', englishName: 'Chinese (Hong Kong)', nativeName: '繁體中文 (香港)', region: 'Hong Kong' },
  { code: 'zu', englishName: 'Zulu', nativeName: 'isiZulu', region: 'South Africa' },
];

export function searchLanguages(query: string): LanguageEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return LANGUAGE_CODES;
  return LANGUAGE_CODES.filter(l =>
    l.code.toLowerCase().includes(q) ||
    l.englishName.toLowerCase().includes(q) ||
    l.nativeName.toLowerCase().includes(q) ||
    (l.region || '').toLowerCase().includes(q)
  );
}
